name: Flutter APK Build

on:
  push:
    branches:
      - flutter  # Trigger only for changes in the flutter branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Flutter SDK
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'

    # Install dependencies
    - name: Install dependencies
      run: flutter pub get

    # Run tests (optional)
    - name: Run tests
      run: flutter test

    # Build APK
    - name: Build APK
      run: flutter build apk --release

    # Upload APK to GitHub folder "APK BUILDS"
    - name: Upload APK to APK BUILDS folder
      run: |
        mkdir -p APK_BUILDS
        mv build/app/outputs/flutter-apk/app-release.apk APK_BUILDS/
      
    # Set up Git credentials
    - name: Set up Git credentials
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://github.com/ha410801/Testing.git flutter
        
    # Debugging
    - name: Check remote
      run: git remote -v

    # Commit APK to the repository
    - name: Commit APK to repository
      run: |
        git add APK_BUILDS/app-release.apk
        git commit -m "Add new APK build"
        git push origin flutter
